tax: 0.01
auction-duration: 172800
auction-setup-time: 30
filler-item: BLACK_STAINED_GLASS_PANE
default-max-auctions: 10
sold-message: true
auto-collect: false
partial-selling: false
admin-permission: auctionhouse.moderator
display-update: 20
auction-announcements: true
